### ISSUE TITLE
There was an error during installation. Please provide the file /tmp/evernode-beta/installer-1699333757.log to Evernode team

### ISSUE THREAD

**Issue by mrnash88** [EvernodeXRPL/evernode-host#109]
Is this where i send the file to? I went to the evernode website but i didn't see a link or email to send the error report. Thanks.

**Comment by kithminisg** [comment]
@mrnash88 , you can attach the logs related to the installation issue here.

**Comment by mrnash88** [comment]
---Sashimono prerequisites installer---
STAGE Installing dependencies
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [672 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2569 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [398 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [59.8 kB]
Get:6 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [896 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/universe i386 Packages [620 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [188 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [96.7 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 DEP-11 Metadata [940 B]
Hit:11 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:12 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [906 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2959 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [481 kB]
Hit:17 https://deb.nodesource.com/node_16.x focal InRelease
Get:18 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [275 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [753 kB]
Get:20 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1128 kB]
Get:21 http://us.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [270 kB]
Get:22 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [414 kB]
Get:23 http://us.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:24 http://us.archive.ubuntu.com/ubuntu focal-backports/main amd64 DEP-11 Metadata [8000 B]
Get:25 http://us.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [30.5 kB]
Fetched 13.1 MB in 11s (1211 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.20).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
jq is already the newest version (1.6-1ubuntu0.20.04.1).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
0 upgraded, 0 newly installed, 0 to remove and 59 not upgraded.
STAGE Configuring fstab
fstab already configured.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
STAGE Configuring grub
Grub already configured.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
Skipping adding existing rule
Skipping adding existing rule (v6)
Running certbot certonly
Requesting a certificate for www.forevernodes.local
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
Error creating new order :: Cannot issue for "www.forevernodes.local": Domain name does not end with a valid public suffix (TLD)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Error when setting up letsencrypt SSL certificate.
Rolling back sashimono installation.
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or directory
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Deleting binaries...
Deleting Sashimono CLI...
rm: cannot remove '/usr/bin/sashi': No such file or directory
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Deleting binaries...
Deleting data directory...
Sashimono uninstalled successfully.
Removing Evernode auto update timer...
Failed to stop evernode-auto-update.timer: Unit evernode-auto-update.timer not loaded.
Failed to disable unit: Unit file evernode-auto-update.timer does not exist.
rm: cannot remove '/etc/systemd/system/evernode-auto-update.timer': No such file or directory
Removing Evernode auto update service...
Failed to stop evernode-auto-update.service: Unit evernode-auto-update.service not loaded.
Failed to disable unit: Unit file evernode-auto-update.service does not exist.
rm: cannot remove '/etc/systemd/system/evernode-auto-update.service': No such file or directory
Rolled back the installation.

**Comment by mrnash88** [comment]
I fixed the previous error now it gives me another one it says:

Could not bind TCP port 80 because it is already in use by another process on this system (such as a web server). Please stop the program in question and then try again.

anyon know what to do? thanks.

**Comment by chalith** [comment]
It seems something has occupied your port 80. SSL setup required port 80 to be free. Check [here](https://docs.evernode.org/en/latest/hosts/evernode-host.html#firewalls-and-ports)

**Comment by mrnash88** [comment]
I deleted apache2 and now it's giving me another error. I posted the new error on a new thread.

**Comment by mrnash88** [comment]
But this is what it said:

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
Domain: [www.forevernodes88.com](http://www.forevernodes88.com/)
Type: dns
Detail: DNS problem: NXDOMAIN looking up A for [www.forevernodes88.com](http://www.forevernodes88.com/) - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for [www.forevernodes88.com](http://www.forevernodes88.com/) - check that a DNS record exists for this domain

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

**Comment by rippleitinnz** [comment]
If you are running Nginx or Apache on your server turn them off while you set up Evernode then restart them once complete of your Evernode host.

If you have no need for a webserver disable the service then it won't be an issue when your certs renew. 

If you're unsure 

> sudo netstat -tulpn | grep :80

**Comment by mrnash88** [comment]
Thanks to everyone for helping me out but I am still getting the error code after typing: sudo netstat -tulpn | grep :80

**This is the error I'm getting:** Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

I have a question: Do I need to buy a domain name like on godaddy.com? Maybe that is the problem because I do not own a domain name. Please if anyone can clarify this. Because the error message I'm getting says: "Ensure that the listed domains point to this machine..." and if that's the case, how can I pointed to this machine if I do buy a domain name. Thanks in advance.

**Comment by ravinsp** [comment]
@mrnash88 Yes you need to and you may be missing other required things as well. That's why it is important to read [important tips](https://docs.evernode.org/en/latest/hosts/evernode-host.html#important-tips-for-installation) before installation.

**Comment by mrnash88** [comment]
@ravinsp I already bought the domain name. I'm still getting the same message. Please help.

**Comment by mrnash88** [comment]
**this is the message i'm getting:**

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: www.forevernodes88.com
  Type:   dns
  Detail: no valid A records found for www.forevernodes88.com; no valid AAAA records found for www.forevernodes88.com

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

**Comment by rippleitinnz** [comment]
Who hosts your domain ?

**Comment by mrnash88** [comment]
@rippleitinnz godaddy

**Comment by rippleitinnz** [comment]
Here’s your issue:Your domain name host is GoDaddy. You have your name servers set tons45.domaincontrol.com - andns46.domaincontrol.comThese should be correct so check your godaddy documentation.You need at least two A records that point to www.forevernodes888.com andforevernodes888.com.Currently you have only forevernodes888.com so create a new A record in your DNS setting and do the following. Currently you are pointing the domain to your internal IP address of 192.168.1.129 and this is where your problem is.You need to point it the the public IP address of the host that is hosting your Evernode instance. If you are hosting from home simply type whatismyip in a google  search and it will tell you. Use this address in your A record. Save it. Once you’ve done that go to yougetsignal.com/tools/openports/ put in your public IP address and port 80 and check if it is open. If it is then you need not do anymore. You can also check to see if port 26301 and 22861 are open. If none are open report back here with the router you are using and the Ubuntu version you are using and I can help you further.One step at a time. On 9/11/2023, at 17:58, mrnash88 ***@***.***> wrote:﻿
this is the message i'm getting:
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
Domain: www.forevernodes88.com
Type:   dns
Detail: no valid A records found for www.forevernodes88.com; no valid AAAA records found for www.forevernodes88.com
Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

**Comment by rippleitinnz** [comment]
> @rippleitinnz godaddy

Here’s your issue:

Your domain name host is GoDaddy. 

You have your name servers set to

ns45.domaincontrol.com - and
ns46.domaincontrol.com

These should be correct so check your godaddy documentation.

You need at least two A records that point to

 www.forevernodes888.com and
forevernodes888.com.

Currently you have only forevernodes888.com so create a new A record in your DNS setting and do the following. Currently you are pointing the domain to your internal IP address of 192.168.1.129 and this is where your problem is.

You need to point it the the public IP address of the host that is hosting your Evernode instance. If you are hosting from home simply type whatismyip in a google  search and it will tell you. Use this address in your A record. Save it. 

Once you’ve done that go to yougetsignal.com/tools/openports/ put in your public IP address and port 80 and check if it is open. If it is then you need not do anymore. 

You can also check to see if port 26301 and 22861 are open. 

If none are open report back here with the router you are using and the Ubuntu version you are using and I can help you further.

One step at a time. 










On 9/11/2023, at 17:58, mrnash88 <notifications@github.com> wrote:

﻿
this is the message i'm getting:

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
Domain: www.forevernodes88.com
Type: dns
Detail: no valid A records found for www.forevernodes88.com; no valid AAAA records found for www.forevernodes88.com

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

**Comment by mrnash88** [comment]
@rippleitinnz ok will do that later today cause I'm at work right now. But when you say to **create a new A record in your DNS setting** do I do that in go daddy or in my computer?

**Comment by rippleitinnz** [comment]
You do that on your domain name settings console at godaddy.

**Comment by mrnash88** [comment]
@rippleitinnz 10-4 Roger that.

**Comment by mrnash88** [comment]
@rippleitinnz None of the ports are open 80, 26301, and 22861. 

I'm using a Spectrum Router

My ubuntu version:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by rippleitinnz** [comment]
In your Ubuntu console do the following

sudo apt install ufw

sudo ufw status

sudo ufw enable

sudo ufw default deny incoming
sudo ufw default allow outgoing

THEN

sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

OR

sudo ufw allow http
sudo ufw allow https

THEN

sudo ufw allow 22861:22874/tcp
sudo ufw allow 26201:26214/tcp

sudo ufw reload 
sudo ufw status

Install Evernode again. If no go then report back.

Goodluck.

**Comment by mrnash88** [comment]
@rippleitinnz **No go..I got this different error report:**

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: www.forevernodes88.com
  Type:   connection
  Detail: 66.215.77.9: Fetching http://www.forevernodes88.com/.well-known/acme-challenge/gNC5S3vBJZ5tSM9CvmvkijZg1_c2kQ2hDwB8VaZr3Es: Timeout during connect (likely firewall problem)

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

**Comment by rippleitinnz** [comment]
Have you tried that port open site to see if your ports are open? And if able to can you display here you ufw status verbose?

**Comment by mrnash88** [comment]
Yes I went to yougetsignal.com and it says: **port 80 is closed** 

attached is my ufw status verbose.

![Screenshot from 2023-11-10 11-30-48](https://github.com/EvernodeXRPL/evernode-host/assets/150109205/ee903925-ee39-456a-81c5-9fc2b7fe4992)

**Comment by mrnash88** [comment]
@rippleitinnz just an update I'm now getting a new error message it says:

**Could not bind TCP port 80 because it is already in use by another process on this system (such as a web server). Please stop the program in question and then try again.**

![Screenshot from 2023-11-10 14-11-08](https://github.com/EvernodeXRPL/evernode-host/assets/150109205/8abd9a03-71b8-4af2-8e34-465e9b06dea5)

**Comment by mrnash88** [comment]
after typing this command: **sudo systemctl stop apache2** and installing Evernode again I got the same error message as before:

**Timeout during connect (likely firewall problem)
Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.**

**Comment by mrnash88** [comment]
yeah no luck. I'm going to reach out to you then. Thanks.
