### ISSUE TITLE
Error in domain verification.

### ISSUE THREAD

**Issue by rippleitinnz** [EvernodeXRPL/evernode-host#136]
After many frustrating hours I am still unable to pass the domain verification stage. It errors when trying to enter domain verification with no usable information to suggest where the error may be. 

Steps to isolate/rectify. 
Ports are open at firewall and server. 
nginx operates fine and domain serves from same server on port 80
Certbot can issue certificate installing its own server and using port 80
Installed new OS and nothing else on server. Failed again

I would like to debug this but can't as it is unknown what process the setup is going through for domain verification.

Perhaps someone could pass me the process so I can attempt a debug and see where the issue lies.

I'm even unable to set up the test-network now, which I ran for many many months without issue

**Comment by ravinsp** [comment]
@rippleitinnz as it was uncovered in the discord channel, the issue arises due to the new validation we are using in the new setup. Basically you host is unable to reach its own domain name which was evident when the `wget` command on the host wasn't able to reach the nginx server hosted on itself via the domain name. If you can get `wget` to reach your nginx by resolving the issue in your network configuration, then the Evernode setup domain verification will also pass.

To make it easy for you to test this here's an independent nodejs script which is based on what's being used inside Sashimono setup. Copy-paste this script into a file on your host and run with *sudo* like `sudo node portcheck.js my.domain.com` (You need to have nodejs, which should be installed already since you ran the setup before.)

```javascript
// Use 'sudo' to run this script. You need nodejs already installed.
// eg. sudo node portcheck.js my.domain.com

const http = require('http');
const process = require('process');

async function test() {

    const domain = process.argv.splice(2)[0];

    if (!domain) {
        console.log('Please specify domain');
        return;
    }

    const port = 80;
    const urlPath = "/sample-port-test";
    const responseString = 'sample-test-response';

    const server = http.createServer((req, res) => {
        if (req.url === urlPath) {
            res.writeHead(200, { "Content-Type": "text/plain" });
            res.end(responseString + '\n');
        } else {
            res.writeHead(404, { 'Content-Type': 'text/plain' });
            res.end('Not Found\n');
        }
    });

    try {
        await new Promise((resolve, reject) => {
            server.on('error', function (e) {
                // We assume this is an error when starting to listen.
                reject("listen_error");
            });

            server.listen(port, () => {
                // Server started. Now send a request via public domain.

                const reqOptions = {
                    hostname: domain,
                    port: port,
                    path: urlPath,
                    method: "GET"
                };

                const req = http.request(reqOptions, (res) => {
                    let data = "";

                    res.on("data", (chunk) => {
                        data += chunk;
                    });

                    // request completion event.
                    res.on("end", () => {
                        server.close();
                        if (data.startsWith(responseString)) {
                            resolve();
                        } else {
                            // Return string does not match our responseString. Most probably response was
                            // sent by some other server. Not by us.
                            reject("domain_error1")
                        }
                    });
                });

                req.on("error", (e) => {
                    server.close();
                    reject("domain_error2")
                });

                req.setTimeout(3000, () => { // 3 second request timeout
                    req.destroy();
                    server.close();
                    reject("domain_error3");
                });

                req.end();
            });
        });

        console.log("Test OK")

    } catch (errorCode) {
        console.log("Test failed", errorCode);
    }
}

test();
```

This nodejs script, listens on port 80 which serves a simple page, and sends a HTTP request to the domain name to see whether it can receive the page served by itself. (Conceptually this is similar to the test you did with nginx and `wget`)

**Comment by rippleitinnz** [comment]
Perfect, thank you.

That'll give me something to work through 

Many thanks

**Comment by rippleitinnz** [comment]
@ravinsp 

Resolved thank you - it was as simple as adding 

127.0.0.1 evernode.onledger.net 

to my hosts file.
