### ISSUE TITLE
 Registration NFT was sent back to the Registration Hook, but the Registration Hook didn't offer the NFT back to me

### ISSUE THREAD

**Issue by Bitbob589** [EvernodeXRPL/evernode-host#289]
Hi, I'm not too knowledgeable about this stuff. I have been told in the discord that after I attempted a transfer my Registration NFT was sent back to the Registration Hook, but the Registration Hook didn't offer the NFT back to me and now I am unable to complete the transfer.

At some point I ran command: 'evernode transfer' thinking it was a short key to the transfer, but I didn't specify a destination

I then ran the command: curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer 

I got to the part where it asks for 500EVR but I already sent the 500EVR before the transfer attempt. 

I think I need to either get the NFT or claim the 500EVR back, I appreciate any help.

I am at your mercy!

**Comment by Leozack9** [comment]
good afternoon. I have a similar problem.I was installing the host, an error came out during the installation. I decided to do it according to the instructions, through the transfer.  Then back installation, error, transfer again. And so a couple of times.  Then at some point in the transfer it began to write "Host is not registered.", I went to the site https://xahauexplorer.com/nft/9501F6E145C58F418FE1180F450A66A442DFFC1CC1DD2B1053D2DAD68F32A52D , found my transaction ID.  I thought to buy back my NFT, but it is not there, it cannot be redeemed. I was told in the chat that he was stuck in a hook. I am waiting for help and a solution. The situation is similar and similar to Bitbob589. 
My wallet address is rQ3mwykALh5ZShEz99B1pMDzmoBs12Y83R


transaction address https://xahauexplorer.com/nft/9501F6E145C58F418FE1180F450A66A442DFFC1CC1DD2B1053D2DAD68F32A52D


https://dashboard.evernode.org/#/host/rQ3mwykALh5ZShEz99B1pMDzmoBs12Y83R

Registration Token Id
9501F6E145C58F418FE1180F450A66A442DFFC1CC1DD2B1053D2DAD68F32A52D

**Comment by Bitbob589** [comment]
Did you get this error: There was an error during installation. Please provide the file /tmp/evernode/installer-1706603900.log to Evernode team. Thank you. <?

I tried to use ChatGPT to fix the issue: (WARNING THIS IS NOT A FIX THIS IS MAY BE THE ISSUE)

ChatGPt said I needed to get the file prepared to send to the Evernode team. 
These are steps I too

Step 1: Locate the Log File
First, you need to access the log file mentioned in the error message. Connect to your VPS via SSH and navigate to the directory containing the log file.
bash: cd /tmp/evernode/

Step 2: Confirm the Log File Exists
Check if the log file is indeed present: Look for installer-1706603900.log in the output.
bash: ls -l

Step 3: View or Retrieve the Log File
To view the contents of the log file:
bash: cat installer-1706603900.log

Step 4: To copy the log file to your local machine, you can use scp (Secure Copy Protocol). On your local machine, run:
scp your_username@your_server_ip:/tmp/evernode/installer-1706603900.log /local/directory

It then asked me to download nodejs on Windows to transfer the file to windows machine. 

It was during this process that the Evernode Install then came back with this error:

Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'bever.host'
Deleted all files relating to certificate bever.host.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/bever.host/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.

**Comment by Leozack9** [comment]
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
Error creating new order :: too many certificates (5) already issued for this exact se>Ask for help or search for solutions at https://community.letsencrypt.org. See the log>
Error when setting up letsencrypt SSL certificate.
Rolling back sashimono installation.
---Sashimono uninstaller---
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or di>
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or direc>
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
rm: cannot remove '/usr/bin/sashi': No such file or directory
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Deleting message board user...
Deleting binaries...
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.


I have this error, and I also tried to change the domain.because the previous time there was a mistake, this one


Transaction result: tesSUCCESS
Waiting for the sell offer F8C922B6A71A7CF4F9310D041DC14C0C34A8D9EF80B94F72269964A9798>
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.>
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'no.evernothostsweb6.ru'
Deleted all files relating to certificate no.evernothostsweb6.ru.
Congratulations! You have successfully revoked the certificate that was located at /et>
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.






but I also have this error


Transaction result: tesSUCCESS
Waiting for the sell offer F8C922B6A71A7CF4F9310D041DC14C0C34A8D9EF80B94F72269964A9798>
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.>
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'no.evernothostsweb6.ru'
Deleted all files relating to certificate no.evernothostsweb6.ru.
Congratulations! You have successfully revoked the certificate that was located at /et>
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.





so I don't even know what else to do.  Now I decided to install it again, and again, during the transfer, the error Host is not registered writes.

**Comment by Bitbob589** [comment]
Did you try install and/or Transfer multiple times? I did.

**Comment by Leozack9** [comment]
Yes, I've tried it 10 times already.

**Comment by Leozack9** [comment]
![Screenshot_134](https://github.com/EvernodeXRPL/evernode-host/assets/157433891/c92b7a08-ffaa-4c79-9be8-0ad106c7c74b)

**Comment by Leozack9** [comment]
this is if I start installing.

**Comment by Leozack9** [comment]
but the mistake is if I start making a transfer
![Screenshot_135](https://github.com/EvernodeXRPL/evernode-host/assets/157433891/0be78de3-22e2-401d-b051-17000c37737c)

**Comment by Leozack9** [comment]
here on the website https://xahauexplorer.com/nft/9501F6E145C58F418FE1180F450A66A442DFFC1CC1DD2B1053D2DAD68F32A52D there is an opportunity to buy NFT again. I bought it back. I'll try to register again now.
![Screenshot_137](https://github.com/EvernodeXRPL/evernode-host/assets/157433891/2e443a07-cf96-47ae-bc95-43749deffd1b)
![Screenshot_136](https://github.com/EvernodeXRPL/evernode-host/assets/157433891/97916e07-f457-4ef3-976a-4d9d0e496cff)

**Comment by Leozack9** [comment]
ошибки ,ошибки , ошибки...Всегда разные.... 
![Screenshot_140](https://github.com/EvernodeXRPL/evernode-host/assets/157433891/49a71a1f-861f-42b0-8997-ee7191ffce0e)
![Screenshot_139](https://github.com/EvernodeXRPL/evernode-host/assets/157433891/dd98107b-a9ff-4331-a578-f1700dc2744c)
![Screenshot_138](https://github.com/EvernodeXRPL/evernode-host/assets/157433891/482a6226-ab78-4068-bb53-f7a4c79ab8ba)

**Comment by Leozack9** [comment]
Hooray, with more than 10 attempts, I was able to return and redeem my NFT. To do this, I first changed the domain/subdomain. Then I did the transfer, there were mistakes, then I replaced the domain again. Then I went to the website https://xahauexplorer.com / logged in via xaman. on the website https://dashboard.evernode.org/#/host I copied the Registration Token Id and therefore found the id https://xahauexplorer.com / and bought out his NFT. Then there were more mistakes, mistakes, mistakes. But I did the transfer, the installation, the transfer , the installation . Just installation , then transfer and installation again. And lo and behold, the host was able to register. I honestly don't know what helped. But initially there was an error in the installation and in the transfer. I think changing the domain helped. And I was missed in the transfer, and I was able to buy out the NFT. Try this in general.

![Screenshot_141](https://github.com/EvernodeXRPL/evernode-host/assets/157433891/cb980a4b-e533-48b7-b971-fbae3dd7a821)
