### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by siasiab1** [EvernodeXRPL/evernode-host#378]
I updated my host to 0.8.3 and averything was ok. I even opt-in for reputation and evernoed status was active.

upon my second login I ran evernode status and got the following error

node01@node01:~$ evernode status
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConfigHelper.readConfig (/usr/bin/sashimono/mb-xrpl/index.js:1:3760)
    at #F (/usr/bin/sashimono/mb-xrpl/index.js:1:40008)
    at Setup.regInfo (/usr/bin/sashimono/mb-xrpl/index.js:1:48723)
    at main (/usr/bin/sashimono/mb-xrpl/index.js:64:476978)
    at /usr/bin/sashimono/mb-xrpl/index.js:64:480577
    at /usr/bin/sashimono/mb-xrpl/index.js:64:480869
    at Object.<anonymous> (/usr/bin/sashimono/mb-xrpl/index.js:64:480908)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
MB_CLI_EXITED
 I installed previous version again and then tryed to install the latest version but got error again and the log is as follow:

2024-05-19 21:47:40 ---Sashimono installer (upgrade)---
2024-05-19 21:47:40 Failed to connect to bus: No such file or directory
2024-05-19 21:47:40 [STAGE] Installing docker packages
2024-05-19 21:47:40 Private docker registry installation skipped
2024-05-19 21:47:40 configuring host setup on Evernode...
2024-05-19 21:47:40 cp: cannot stat '/tmp/tmp.IhLU6DkqO7/reputation-contract': No such file or directory
2024-05-19 21:47:40 [STAGE] Configuring Sashimono services
2024-05-19 21:47:40 Creating cgroup rules...
2024-05-19 21:47:40 Configuring sashimono agent service...
2024-05-19 21:47:40 Existing Sashimono data directory found. Updating...
2024-05-19 21:47:40 SyntaxError: Unexpected end of JSON input
2024-05-19 21:47:40     at JSON.parse (<anonymous>)
2024-05-19 21:47:40     at ConfigHelper.readConfig (/usr/bin/sashimono/mb-xrpl/index.js:1:3760)
2024-05-19 21:47:40     at #F (/usr/bin/sashimono/mb-xrpl/index.js:1:40008)
2024-05-19 21:47:40     at Setup.upgrade (/usr/bin/sashimono/mb-xrpl/index.js:1:50135)
2024-05-19 21:47:40     at main (/usr/bin/sashimono/mb-xrpl/index.js:64:477155)
2024-05-19 21:47:40     at /usr/bin/sashimono/mb-xrpl/index.js:64:480577
2024-05-19 21:47:40     at /usr/bin/sashimono/mb-xrpl/index.js:64:480869
2024-05-19 21:47:40     at Object.<anonymous> (/usr/bin/sashimono/mb-xrpl/index.js:64:480908)
2024-05-19 21:47:40     at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-05-19 21:47:40     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-05-19 21:47:40 MB_CLI_EXITED

I tried to Transfer my account but got the following error:

Transferring host...
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConfigHelper.readConfig (/usr/bin/sashimono/mb-xrpl/index.js:1:3760)
    at #F (/usr/bin/sashimono/mb-xrpl/index.js:1:40008)
    at Setup.transfer (/usr/bin/sashimono/mb-xrpl/index.js:1:52166)
    at main (/usr/bin/sashimono/mb-xrpl/index.js:64:476815)
    at /usr/bin/sashimono/mb-xrpl/index.js:64:480577
    at /usr/bin/sashimono/mb-xrpl/index.js:64:480869
    at Object.<anonymous> (/usr/bin/sashimono/mb-xrpl/index.js:64:480908)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
MB_CLI_EXITED
Evernode transfer initiation was failed. Still do you want to continue the unistallation? [Y/n] n

Aborting unistallation. Try again later.

I kindly appreciate your assistance

**Comment by chalith** [comment]
Have you manually updated any config files? Try again transferring using the command starting with `curl` here https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration. Do not install the older version over new version.

**Comment by siasiab1** [comment]
I followed your instruction when I want to transfer it gives the following error:

Do you want to set the current host account as the transferee's account? [Y/n] y

Transferring host...
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConfigHelper.readConfig (/usr/bin/sashimono/mb-xrpl/index.js:1:3760)
    at #F (/usr/bin/sashimono/mb-xrpl/index.js:1:40008)
    at Setup.transfer (/usr/bin/sashimono/mb-xrpl/index.js:1:52166)
    at main (/usr/bin/sashimono/mb-xrpl/index.js:64:476815)
    at /usr/bin/sashimono/mb-xrpl/index.js:64:480577
    at /usr/bin/sashimono/mb-xrpl/index.js:64:480869
    at Object.<anonymous> (/usr/bin/sashimono/mb-xrpl/index.js:64:480908)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
MB_CLI_EXITED
Evernode transfer initiation was failed. Still do you want to continue the unistallation? [Y/n] 

what shall I do? Shall I uninstall anyway?

**Comment by siasiab1** [comment]
Kindly my node is down for 1 day and I appreciate your assistance

Evernode transfer initiation was failed but is asking if i want to continue installation. What shall i do?

**Comment by chalith** [comment]
Can you try above transfer command on a separate machine and check if it succeeds If so do a `evernode uninstall`.
Before you do, make sure to backup both your host and reputation secrets

**Comment by JULIEN9159** [comment]
Hello guys,

Same issue here :
My host where reputation contract is running is not properly working anymore. 

Since some days no issue at all, rep contract working fine (except not at every moment, but still was showing active), and now it's on "activating" with this display when running status :

Evernode reputationd status: activating
Your reputationd account details are stored in /etc/sashimono/reputationd/reputationd.cfg
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
    at #H (/usr/bin/sashimono/reputationd/index.js:1:20071)
    at Setup.repInfo (/usr/bin/sashimono/reputationd/index.js:1:22181)
    at main (/usr/bin/sashimono/reputationd/index.js:124:205782)
    at /usr/bin/sashimono/reputationd/index.js:124:207006
    at /usr/bin/sashimono/reputationd/index.js:124:207308
    at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
REPUTATIOND_EXITED
Error getting reputation status


From now,  even Evernode status is not working properly and my node became offline :

Evernode reputationd status: activating
Your reputationd account details are stored in /etc/sashimono/reputationd/reputationd.cfg
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
    at #H (/usr/bin/sashimono/reputationd/index.js:1:20071)
    at Setup.repInfo (/usr/bin/sashimono/reputationd/index.js:1:22181)
    at main (/usr/bin/sashimono/reputationd/index.js:124:205782)
    at /usr/bin/sashimono/reputationd/index.js:124:207006
    at /usr/bin/sashimono/reputationd/index.js:124:207308
    at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
REPUTATIOND_EXITED
Error getting reputation status






You can also find the log (Evernode log) here :

May 23 07:35:09 evernode101 node[4104]:     at JSON.parse (<anonymous>)
May 23 07:35:09 evernode101 node[4104]:     at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
May 23 07:35:09 evernode101 node[4104]:     at #m (/usr/bin/sashimono/reputationd/index.js:1:19589)
May 23 07:35:09 evernode101 node[4104]:     at ReputationD.init (/usr/bin/sashimono/reputationd/index.js:1:7117)
May 23 07:35:09 evernode101 node[4104]:     at main (/usr/bin/sashimono/reputationd/index.js:124:206764)
May 23 07:35:09 evernode101 node[4104]:     at /usr/bin/sashimono/reputationd/index.js:124:207006
May 23 07:35:09 evernode101 node[4104]:     at /usr/bin/sashimono/reputationd/index.js:124:207308
May 23 07:35:09 evernode101 node[4104]:     at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
May 23 07:35:09 evernode101 node[4104]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 23 07:35:09 evernode101 node[4104]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 23 07:35:09 evernode101 node[4104]: 20240523 07:35:09 [dbg] Evernode ReputationD exiting with error.
May 23 07:35:09 evernode101 node[4104]: 20240523 07:35:09 [dbg] REPUTATIOND_EXITED
May 23 07:35:09 evernode101 systemd[821]: sashimono-reputationd.service: Main process exited, code=exited, status=1/FAILURE
May 23 07:35:09 evernode101 systemd[821]: sashimono-reputationd.service: Failed with result 'exit-code'.
May 23 07:35:14 evernode101 systemd[821]: sashimono-reputationd.service: Scheduled restart job, restart counter is at 164.
May 23 07:35:14 evernode101 systemd[821]: Stopped Running Evernode reputation for reward distribution..
May 23 07:35:14 evernode101 systemd[821]: Started Running Evernode reputation for reward distribution..
May 23 07:35:14 evernode101 node[4118]: 20240523 07:35:14 [dbg] Starting the Evernode Xahau reputationd.
May 23 07:35:14 evernode101 node[4118]: 20240523 07:35:14 [dbg] Data dir: /etc/sashimono/reputationd
May 23 07:35:14 evernode101 node[4118]: 20240523 07:35:14 [dbg] Using message board config: /etc/sashimono/mb-xrpl/mb-xrpl.cfg
May 23 07:35:14 evernode101 node[4118]: 20240523 07:35:14 [dbg] SyntaxError: Unexpected end of JSON input
May 23 07:35:14 evernode101 node[4118]:     at JSON.parse (<anonymous>)
May 23 07:35:14 evernode101 node[4118]:     at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
May 23 07:35:14 evernode101 node[4118]:     at #m (/usr/bin/sashimono/reputationd/index.js:1:19589)
May 23 07:35:14 evernode101 node[4118]:     at ReputationD.init (/usr/bin/sashimono/reputationd/index.js:1:7117)
May 23 07:35:14 evernode101 node[4118]:     at main (/usr/bin/sashimono/reputationd/index.js:124:206764)
May 23 07:35:14 evernode101 node[4118]:     at /usr/bin/sashimono/reputationd/index.js:124:207006
May 23 07:35:14 evernode101 node[4118]:     at /usr/bin/sashimono/reputationd/index.js:124:207308
May 23 07:35:14 evernode101 node[4118]:     at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
May 23 07:35:14 evernode101 node[4118]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 23 07:35:14 evernode101 node[4118]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 23 07:35:14 evernode101 node[4118]: 20240523 07:35:14 [dbg] Evernode ReputationD exiting with error.
May 23 07:35:14 evernode101 node[4118]: 20240523 07:35:14 [dbg] REPUTATIOND_EXITED
May 23 07:35:14 evernode101 systemd[821]: sashimono-reputationd.service: Main process exited, code=exited, status=1/FAILURE
May 23 07:35:14 evernode101 systemd[821]: sashimono-reputationd.service: Failed with result 'exit-code'.
May 23 07:35:19 evernode101 systemd[821]: sashimono-reputationd.service: Scheduled restart job, restart counter is at 165.
May 23 07:35:19 evernode101 systemd[821]: Stopped Running Evernode reputation for reward distribution..
May 23 07:35:19 evernode101 systemd[821]: Started Running Evernode reputation for reward distribution..
May 23 07:35:20 evernode101 node[4134]: 20240523 07:35:20 [dbg] Starting the Evernode Xahau reputationd.
May 23 07:35:20 evernode101 node[4134]: 20240523 07:35:20 [dbg] Data dir: /etc/sashimono/reputationd
May 23 07:35:20 evernode101 node[4134]: 20240523 07:35:20 [dbg] Using message board config: /etc/sashimono/mb-xrpl/mb-xrpl.cfg
May 23 07:35:20 evernode101 node[4134]: 20240523 07:35:20 [dbg] SyntaxError: Unexpected end of JSON input
May 23 07:35:20 evernode101 node[4134]:     at JSON.parse (<anonymous>)
May 23 07:35:20 evernode101 node[4134]:     at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
May 23 07:35:20 evernode101 node[4134]:     at #m (/usr/bin/sashimono/reputationd/index.js:1:19589)
May 23 07:35:20 evernode101 node[4134]:     at ReputationD.init (/usr/bin/sashimono/reputationd/index.js:1:7117)
May 23 07:35:20 evernode101 node[4134]:     at main (/usr/bin/sashimono/reputationd/index.js:124:206764)
May 23 07:35:20 evernode101 node[4134]:     at /usr/bin/sashimono/reputationd/index.js:124:207006
May 23 07:35:20 evernode101 node[4134]:     at /usr/bin/sashimono/reputationd/index.js:124:207308
May 23 07:35:20 evernode101 node[4134]:     at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
May 23 07:35:20 evernode101 node[4134]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 23 07:35:20 evernode101 node[4134]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 23 07:35:20 evernode101 node[4134]: 20240523 07:35:20 [dbg] Evernode ReputationD exiting with error.
May 23 07:35:20 evernode101 node[4134]: 20240523 07:35:20 [dbg] REPUTATIOND_EXITED
May 23 07:35:20 evernode101 systemd[821]: sashimono-reputationd.service: Main process exited, code=exited, status=1/FAILURE
May 23 07:35:20 evernode101 systemd[821]: sashimono-reputationd.service: Failed with result 'exit-code'.
May 23 07:35:25 evernode101 systemd[821]: sashimono-reputationd.service: Scheduled restart job, restart counter is at 166.
May 23 07:35:25 evernode101 systemd[821]: Stopped Running Evernode reputation for reward distribution..
May 23 07:35:25 evernode101 systemd[821]: Started Running Evernode reputation for reward distribution..
May 23 07:35:26 evernode101 node[4148]: 20240523 07:35:26 [dbg] Starting the Evernode Xahau reputationd.
May 23 07:35:26 evernode101 node[4148]: 20240523 07:35:26 [dbg] Data dir: /etc/sashimono/reputationd
May 23 07:35:26 evernode101 node[4148]: 20240523 07:35:26 [dbg] Using message board config: /etc/sashimono/mb-xrpl/mb-xrpl.cfg
May 23 07:35:26 evernode101 node[4148]: 20240523 07:35:26 [dbg] SyntaxError: Unexpected end of JSON input
May 23 07:35:26 evernode101 node[4148]:     at JSON.parse (<anonymous>)
May 23 07:35:26 evernode101 node[4148]:     at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
May 23 07:35:26 evernode101 node[4148]:     at #m (/usr/bin/sashimono/reputationd/index.js:1:19589)
May 23 07:35:26 evernode101 node[4148]:     at ReputationD.init (/usr/bin/sashimono/reputationd/index.js:1:7117)
May 23 07:35:26 evernode101 node[4148]:     at main (/usr/bin/sashimono/reputationd/index.js:124:206764)
May 23 07:35:26 evernode101 node[4148]:     at /usr/bin/sashimono/reputationd/index.js:124:207006
May 23 07:35:26 evernode101 node[4148]:     at /usr/bin/sashimono/reputationd/index.js:124:207308
May 23 07:35:26 evernode101 node[4148]:     at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
May 23 07:35:26 evernode101 node[4148]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 23 07:35:26 evernode101 node[4148]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 23 07:35:26 evernode101 node[4148]: 20240523 07:35:26 [dbg] Evernode ReputationD exiting with error.
May 23 07:35:26 evernode101 node[4148]: 20240523 07:35:26 [dbg] REPUTATIOND_EXITED
May 23 07:35:26 evernode101 systemd[821]: sashimono-reputationd.service: Main process exited, code=exited, status=1/FAILURE
May 23 07:35:26 evernode101 systemd[821]: sashimono-reputationd.service: Failed with result 'exit-code'.
May 23 07:35:31 evernode101 systemd[821]: sashimono-reputationd.service: Scheduled restart job, restart counter is at 167.
May 23 07:35:31 evernode101 systemd[821]: Stopped Running Evernode reputation for reward distribution..
May 23 07:35:31 evernode101 systemd[821]: Started Running Evernode reputation for reward distribution..
May 23 07:35:32 evernode101 node[4186]: 20240523 07:35:32 [dbg] Starting the Evernode Xahau reputationd.
May 23 07:35:32 evernode101 node[4186]: 20240523 07:35:32 [dbg] Data dir: /etc/sashimono/reputationd
May 23 07:35:32 evernode101 node[4186]: 20240523 07:35:32 [dbg] Using message board config: /etc/sashimono/mb-xrpl/mb-xrpl.cfg
May 23 07:35:32 evernode101 node[4186]: 20240523 07:35:32 [dbg] SyntaxError: Unexpected end of JSON input
May 23 07:35:32 evernode101 node[4186]:     at JSON.parse (<anonymous>)
May 23 07:35:32 evernode101 node[4186]:     at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
May 23 07:35:32 evernode101 node[4186]:     at #m (/usr/bin/sashimono/reputationd/index.js:1:19589)
May 23 07:35:32 evernode101 node[4186]:     at ReputationD.init (/usr/bin/sashimono/reputationd/index.js:1:7117)
May 23 07:35:32 evernode101 node[4186]:     at main (/usr/bin/sashimono/reputationd/index.js:124:206764)
May 23 07:35:32 evernode101 node[4186]:     at /usr/bin/sashimono/reputationd/index.js:124:207006
May 23 07:35:32 evernode101 node[4186]:     at /usr/bin/sashimono/reputationd/index.js:124:207308
May 23 07:35:32 evernode101 node[4186]:     at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
May 23 07:35:32 evernode101 node[4186]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 23 07:35:32 evernode101 node[4186]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 23 07:35:32 evernode101 node[4186]: 20240523 07:35:32 [dbg] Evernode ReputationD exiting with error.
May 23 07:35:32 evernode101 node[4186]: 20240523 07:35:32 [dbg] REPUTATIOND_EXITED
May 23 07:35:32 evernode101 systemd[821]: sashimono-reputationd.service: Main process exited, code=exited, status=1/FAILURE
May 23 07:35:32 evernode101 systemd[821]: sashimono-reputationd.service: Failed with result 'exit-code'.
May 23 07:35:37 evernode101 systemd[821]: sashimono-reputationd.service: Scheduled restart job, restart counter is at 168.
May 23 07:35:37 evernode101 systemd[821]: Stopped Running Evernode reputation for reward distribution..
May 23 07:35:37 evernode101 systemd[821]: Started Running Evernode reputation for reward distribution..
May 23 07:35:38 evernode101 node[4233]: 20240523 07:35:38 [dbg] Starting the Evernode Xahau reputationd.
May 23 07:35:38 evernode101 node[4233]: 20240523 07:35:38 [dbg] Data dir: /etc/sashimono/reputationd
May 23 07:35:38 evernode101 node[4233]: 20240523 07:35:38 [dbg] Using message board config: /etc/sashimono/mb-xrpl/mb-xrpl.cfg
May 23 07:35:38 evernode101 node[4233]: 20240523 07:35:38 [dbg] SyntaxError: Unexpected end of JSON input
May 23 07:35:38 evernode101 node[4233]:     at JSON.parse (<anonymous>)
May 23 07:35:38 evernode101 node[4233]:     at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
May 23 07:35:38 evernode101 node[4233]:     at #m (/usr/bin/sashimono/reputationd/index.js:1:19589)
May 23 07:35:38 evernode101 node[4233]:     at ReputationD.init (/usr/bin/sashimono/reputationd/index.js:1:7117)
May 23 07:35:38 evernode101 node[4233]:     at main (/usr/bin/sashimono/reputationd/index.js:124:206764)
May 23 07:35:38 evernode101 node[4233]:     at /usr/bin/sashimono/reputationd/index.js:124:207006
May 23 07:35:38 evernode101 node[4233]:     at /usr/bin/sashimono/reputationd/index.js:124:207308
May 23 07:35:38 evernode101 node[4233]:     at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
May 23 07:35:38 evernode101 node[4233]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 23 07:35:38 evernode101 node[4233]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 23 07:35:38 evernode101 node[4233]: 20240523 07:35:38 [dbg] Evernode ReputationD exiting with error.
May 23 07:35:38 evernode101 node[4233]: 20240523 07:35:38 [dbg] REPUTATIOND_EXITED
May 23 07:35:38 evernode101 systemd[821]: sashimono-reputationd.service: Main process exited, code=exited, status=1/FAILURE
May 23 07:35:38 evernode101 systemd[821]: sashimono-reputationd.service: Failed with result 'exit-code'.
May 23 07:35:43 evernode101 systemd[821]: sashimono-reputationd.service: Scheduled restart job, restart counter is at 169.
May 23 07:35:43 evernode101 systemd[821]: Stopped Running Evernode reputation for reward distribution..
May 23 07:35:43 evernode101 systemd[821]: Started Running Evernode reputation for reward distribution..
May 23 07:35:44 evernode101 node[4293]: 20240523 07:35:44 [dbg] Starting the Evernode Xahau reputationd.
May 23 07:35:44 evernode101 node[4293]: 20240523 07:35:44 [dbg] Data dir: /etc/sashimono/reputationd
May 23 07:35:44 evernode101 node[4293]: 20240523 07:35:44 [dbg] Using message board config: /etc/sashimono/mb-xrpl/mb-xrpl.cfg
May 23 07:35:44 evernode101 node[4293]: 20240523 07:35:44 [dbg] SyntaxError: Unexpected end of JSON input
May 23 07:35:44 evernode101 node[4293]:     at JSON.parse (<anonymous>)
May 23 07:35:44 evernode101 node[4293]:     at ConfigHelper.readConfig (/usr/bin/sashimono/reputationd/index.js:1:2661)
May 23 07:35:44 evernode101 node[4293]:     at #m (/usr/bin/sashimono/reputationd/index.js:1:19589)
May 23 07:35:44 evernode101 node[4293]:     at ReputationD.init (/usr/bin/sashimono/reputationd/index.js:1:7117)
May 23 07:35:44 evernode101 node[4293]:     at main (/usr/bin/sashimono/reputationd/index.js:124:206764)
May 23 07:35:44 evernode101 node[4293]:     at /usr/bin/sashimono/reputationd/index.js:124:207006
May 23 07:35:44 evernode101 node[4293]:     at /usr/bin/sashimono/reputationd/index.js:124:207308
May 23 07:35:44 evernode101 node[4293]:     at Object.<anonymous> (/usr/bin/sashimono/reputationd/index.js:124:207329)
May 23 07:35:44 evernode101 node[4293]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 23 07:35:44 evernode101 node[4293]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 23 07:35:44 evernode101 node[4293]: 20240523 07:35:44 [dbg] Evernode ReputationD exiting with error.
May 23 07:35:44 evernode101 node[4293]: 20240523 07:35:44 [dbg] REPUTATIOND_EXITED
May 23 07:35:44 evernode101 systemd[821]: sashimono-reputationd.service: Main process exited, code=exited, status=1/FAILURE
May 23 07:35:44 evernode101 systemd[821]: sashimono-reputationd.service: Failed with result 'exit-code'.

**Comment by JULIEN9159** [comment]
It seems the configuration file is totally missing :
/etc/sashimono/reputationd/reputationd.cfg is empty.....

How to recover? Someone has an example ?

**Comment by JULIEN9159** [comment]
Ok. I opted out and then opted in --> reputation contracts working back.

However, it seems my previous lease has not end properly, leading to having 2 lease used and only 1 available 

1st was initial RC
2nd is new RC
3rd is available

**Comment by JULIEN9159** [comment]
Trying to opt out, then delete the instances, but evernode list is giving no information, only [].

I tried to delete the txn hash that seems to be linked to the URI token create selloffer, but getting error :
![Screenshot_2024-05-23-10-26-11-008_com server auditor ssh client](https://github.com/EvernodeXRPL/evernode-host/assets/157272000/3c3255b2-bb2e-4997-9510-1cce44b765c6)
![Screenshot_2024-05-23-10-25-40-575_com server auditor ssh client](https://github.com/EvernodeXRPL/evernode-host/assets/157272000/55a8b728-cb39-4cb0-b79c-4f8c3ddb8817)
![Screenshot_2024-05-23-10-26-52-129_com server auditor ssh client](https://github.com/EvernodeXRPL/evernode-host/assets/157272000/1a6aa7c7-f2d9-4495-ac89-52148eeb702a)

**Comment by JULIEN9159** [comment]
Update : it seems since the instance not available since rep contract crash, even if opt out and opt in, with a new lease intake, the command "Evernode list" is not showing the new rep contract instance name (only showing [])

**Comment by chalith** [comment]
@JULIEN9159 it seems your reputationd is still inactive, Have you opted in again?
And also to fix leases try running `evernode offerlease` command and it'll create missing lease offers. If it doesn't not fix the lease problem. Try changing the instance count to a different value (probably 4) using `evernode config resources` command and then again change it back to original size (in your case 3)

**Comment by JULIEN9159** [comment]
My reputation was active. But through another instance.

I followed your advice.: offerlease not Working, I tried with config ressources, ans it worked. I put 0 0 0 4 and then back to 0 0 0 3. Thank for the update. I will monitor if any trouble as I opted-in again.

Also, I hope the team will be able to identify the concern and fix it in future update.

Again thank you @chalith

**Comment by JULIEN9159** [comment]
Hello,

Again this morning, after 1 day running well, I got below failure : 
![Uploading Screenshot_2024-05-28-11-44-09-974_com.server.auditor.ssh.client.png…]()

**Comment by JULIEN9159** [comment]
My disk seems full but I don't understand why

**Comment by chalith** [comment]
Hi @JULIEN9159  what's the latest status of the issue after the patch?

**Comment by JULIEN9159** [comment]
Hello,

After changing my VM I didn't get any issue (5 days running ol with opt-in). Now I patched it but can't see the difference as no concern anymore.

Have a good day

**Comment by chalith** [comment]
Thank you @JULIEN9159. We are closing the issue
