### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by Greypimps** [EvernodeXRPL/evernode-host#404]
hello im not very good with this stuff..
but how do you check your ssl certificate? i think i use the default or havent set one up when i first install the host.  Also i just add some evrs to my rep account but my rep is zero? can i get help or explanation please??

**Comment by du1ana** [comment]
hi, validity of your SSL certificate will be checked in reputationD. you can run `sudo -u sashireputationd bash -c 'journalctl --user -u sashimono-reputationd | tail -n 250'` to view the logs to determine the status of it.

please [refer to this documentation to diagnose reputationd related issues](https://docs.evernode.org/en/latest/hosts/evernode-diagnostics.html#handling-reputation-assessment-observations)

**Comment by Greypimps** [comment]
Got a question, do we have to manually opt in to reputation every few days
or does it automatically olt in.. seem my reputation goes to zero every 2
days and have ti run the opt in command again..

**Comment by du1ana** [comment]
No, you do not need to manually opt in periodically. However, as the [reputation service is down right now](https://discord.com/channels/953758352280813618/956338783169687622/1280801206276587541) due to a bug in Xahau, we are unable to look into this issue at the moment.

**After the reputation service is resumed again following the Xahaud amendment**, please refer to [this documentation to diagnose your issue](https://docs.evernode.org/en/latest/hosts/evernode-diagnostics.html#handling-reputation-assessment-observations). I will close this issue but please feel free to reopen if there are any unresolved concerns.
