### ISSUE TITLE
relutationd opt in 

### ISSUE THREAD

**Issue by Greypimps** [EvernodeXRPL/evernode-host#428]
do we need to manually opt in every few days?? seem my rep goes to zero on the dashboard every few days and i have to keep opting in everyvtwo days.  Thought if ibhhave enough xah it would be automatic..

**Comment by du1ana** [comment]
No, you do not need to manually opt in periodically. However, as the [reputation service is down right now](https://discord.com/channels/953758352280813618/956338783169687622/1280801206276587541) due to a bug in Xahau, we are unable to look into this issue at the moment.

**After the reputation service is resumed again following the Xahaud amendment**, please refer to [this documentation to diagnose your issue](https://docs.evernode.org/en/latest/hosts/evernode-diagnostics.html#handling-reputation-assessment-observations). I will close this issue but please feel free to reopen if there are any unresolved concerns.
