### ISSUE TITLE
I do not receive a reward. Reputation slowly rises to 200+ and drops again.

### ISSUE THREAD

**Issue by AndriiVlasiuk1991** [EvernodeXRPL/evernode-host#429]
Greetings. I have a similar problem. I don't get rewards and the reputation barely goes up to 200+, and if it goes up it goes down again.
I applied your commands.
[MB-XRPL log.txt](https://github.com/user-attachments/files/16917208/MB-XRPL.log.txt)
[Reputationd log.txt](https://github.com/user-attachments/files/16917209/Reputationd.log.txt)
On all hosts I see a line with an error:
Sep 07 09:01:07 Ever-1 node[856]: 20240907 09:01:07 [err] Error occurred while reading the scores: wss://107.152.47.106:26201 connection failed.
I will be grateful for your help. I am waiting for your answer.

**Comment by du1ana** [comment]
Hi, right now the [rewards are paused](https://discord.com/channels/953758352280813618/956338783169687622/1280801206276587541) due to a bug in Xahau. While rewards are paused, please opt out of the reputation system until further notice. I will be closing this issue, but if there are any unresolved concerns after rewards are resumed again, please feel free to reopen. Thanks.
